package com.airbus.alten.cacau.logic;

public enum EnumSearchLogic {

	NAME,
	DESCRIPTION,
	EMITTER,
	LABEL,
	SOURCE,
	
	NAME_DESCRIPTION,
	NAME_EMITTER,
	NAME_SOURCE,
	NAME_LABEL,

	DESCRIPTION_EMITTER,
	DESCRIPTION_SOURCE,
	DESCRIPTION_LABEL,
	
	EMITTER_SOURCE,
	EMITTER_LABEL,
	
	SOURCE_LABEL,
	
	NAME_DESCRIPTION_EMITTER,
	NAME_DESCRIPTION_SOURCE,
	NAME_DESCRIPTION_LABEL,
	
	DESCRIPTION_EMITTER_SOURCE,
	DESCRIPTION_EMITTER_LABEL,
	
	EMITTER_SOURCE_LABEL,
	EMITTER_SOURCE_NAME,
	EMITTER_LABEL_NAME,
	
	SOURCE_LABEL_NAME,
	SOURCE_LABEL_DESCRIPTION,

	NAME_DESCRIPTION_EMITTER_LABEL,
	NAME_DESCRIPTION_EMITTER_SOURCE,
	NAME_DESCRIPTION_SOURCE_LABEL,
	
	DESCRIPTION_EMITTER_SOURCE_LABEL,
	
	EMITTER_SOURCE_LABEL_NAME,
	
	NAME_DESCRIPTION_EMITTER_SOURCE_LABEL,
	
}
