//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.03 at 10:24:08 PM CET 
//


package com.airbus.alten.cacau.model.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}PROGRAM" maxOccurs="unbounded"/>
 *         &lt;element ref="{}AIRLINE" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}EQUIPMENT" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "program",
    "airline",
    "equipment"
})
@XmlRootElement(name = "APPLICABILITY")
public class APPLICABILITY {

    @XmlElement(name = "PROGRAM", required = true)
    protected List<PROGRAM> program;
    @XmlElement(name = "AIRLINE")
    protected List<AIRLINE> airline;
    @XmlElement(name = "EQUIPMENT")
    protected List<EQUIPMENT> equipment;

    /**
     * Gets the value of the program property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the program property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPROGRAM().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PROGRAM }
     * 
     * 
     */
    public List<PROGRAM> getPROGRAM() {
        if (program == null) {
            program = new ArrayList<PROGRAM>();
        }
        return this.program;
    }

    /**
     * Gets the value of the airline property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the airline property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAIRLINE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AIRLINE }
     * 
     * 
     */
    public List<AIRLINE> getAIRLINE() {
        if (airline == null) {
            airline = new ArrayList<AIRLINE>();
        }
        return this.airline;
    }

    /**
     * Gets the value of the equipment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the equipment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEQUIPMENT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EQUIPMENT }
     * 
     * 
     */
    public List<EQUIPMENT> getEQUIPMENT() {
        if (equipment == null) {
            equipment = new ArrayList<EQUIPMENT>();
        }
        return this.equipment;
    }

	public void setPROGRAM(List<PROGRAM> program) {
		this.program = program;
	}

	public void setAIRLINE(List<AIRLINE> airline) {
		this.airline = airline;
	}

	public void setEQUIPMENT(List<EQUIPMENT> equipment) {
		this.equipment = equipment;
	}

    
}
