//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.03 at 10:24:08 PM CET 
//


package com.airbus.alten.cacau.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}CONTENT"/>
 *         &lt;element ref="{}EXPLORATION" minOccurs="0"/>
 *         &lt;element ref="{}DUMMY" minOccurs="0"/>
 *         &lt;element ref="{}YPBATCH"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content",
    "exploration",
    "dummy",
    "ypbatch"
})
@XmlRootElement(name = "CONFIGURATION")
public class CONFIGURATION {

    @XmlElement(name = "CONTENT", required = true)
    protected CONTENT content;
    @XmlElement(name = "EXPLORATION")
    protected EXPLORATION exploration;
    @XmlElement(name = "DUMMY")
    protected DUMMY dummy;
    @XmlElement(name = "YPBATCH", required = true)
    protected YPBATCH ypbatch;

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link CONTENT }
     *     
     */
    public CONTENT getCONTENT() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link CONTENT }
     *     
     */
    public void setCONTENT(CONTENT value) {
        this.content = value;
    }

    /**
     * Gets the value of the exploration property.
     * 
     * @return
     *     possible object is
     *     {@link EXPLORATION }
     *     
     */
    public EXPLORATION getEXPLORATION() {
        return exploration;
    }

    /**
     * Sets the value of the exploration property.
     * 
     * @param value
     *     allowed object is
     *     {@link EXPLORATION }
     *     
     */
    public void setEXPLORATION(EXPLORATION value) {
        this.exploration = value;
    }

    /**
     * Gets the value of the dummy property.
     * 
     * @return
     *     possible object is
     *     {@link DUMMY }
     *     
     */
    public DUMMY getDUMMY() {
        return dummy;
    }

    /**
     * Sets the value of the dummy property.
     * 
     * @param value
     *     allowed object is
     *     {@link DUMMY }
     *     
     */
    public void setDUMMY(DUMMY value) {
        this.dummy = value;
    }

    /**
     * Gets the value of the ypbatch property.
     * 
     * @return
     *     possible object is
     *     {@link YPBATCH }
     *     
     */
    public YPBATCH getYPBATCH() {
        return ypbatch;
    }

    /**
     * Sets the value of the ypbatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link YPBATCH }
     *     
     */
    public void setYPBATCH(YPBATCH value) {
        this.ypbatch = value;
    }

}
