//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.03 at 10:24:08 PM CET 
//

package com.airbus.alten.cacau.model.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}APPLICABILITY"/>
 *         &lt;element ref="{}EMITTER" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{}contentid use="required""/>
 *       &lt;attribute ref="{}title"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "applicability",
    "emitter"
})
@XmlRootElement(name = "CONTENT")
public class CONTENT {

    @XmlElement(name = "APPLICABILITY", required = true)
    protected APPLICABILITY applicability;
    @XmlElement(name = "EMITTER", required = true)
    protected List<EMITTER> emitter;
    @XmlAttribute(name = "contentid", required = true)
    protected int contentid;
    @XmlAttribute(name = "title")
    protected String title;

    /**
     * Gets the value of the applicability property.
     * 
     * @return
     *     possible object is
     *     {@link APPLICABILITY }
     *     
     */
    public APPLICABILITY getAPPLICABILITY() {
        return applicability;
    }

    /**
     * Sets the value of the applicability property.
     * 
     * @param value
     *     allowed object is
     *     {@link APPLICABILITY }
     *     
     */
    public void setAPPLICABILITY(APPLICABILITY value) {
        this.applicability = value;
    }

    /**
     * Gets the value of the emitter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the emitter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEMITTER().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EMITTER }
     * 
     * 
     */
    public List<EMITTER> getEMITTER() {
        if (emitter == null) {
            emitter = new ArrayList<EMITTER>();
        }
        return this.emitter;
    }

    /**
     * Gets the value of the contentid property.
     * 
     */
    public int getContentid() {
        return contentid;
    }

    /**
     * Sets the value of the contentid property.
     * 
     */
    public void setContentid(int value) {
        this.contentid = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

	public void setEMITTER(List<EMITTER> emitter) {
		this.emitter = emitter;
	}

    
}
