//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.03 at 10:24:08 PM CET 
//


package com.airbus.alten.cacau.model.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}PARAMETER" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{}emitterid use="required""/>
 *       &lt;attribute ref="{}equipmentCode use="required""/>
 *       &lt;attribute ref="{}emitterName use="required""/>
 *       &lt;attribute ref="{}side use="required""/>
 *       &lt;attribute ref="{}busfunction"/>
 *       &lt;attribute ref="{}inlay"/>
 *       &lt;attribute ref="{}hiPinNumber"/>
 *       &lt;attribute ref="{}hiPinChar"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "parameter"
})
@XmlRootElement(name = "EMITTER")
public class EMITTER {

    @XmlElement(name = "PARAMETER", required = true)
    protected List<PARAMETER> parameter;
    @XmlAttribute(name = "emitterid", required = true)
    protected int emitterid;
    @XmlAttribute(name = "equipmentCode", required = true)
    protected String equipmentCode;
    @XmlAttribute(name = "emitterName", required = true)
    protected String emitterName;
    @XmlAttribute(name = "side", required = true)
    protected int side;
    @XmlAttribute(name = "busfunction")
    protected String busfunction;
    @XmlAttribute(name = "inlay")
    protected String inlay;
    @XmlAttribute(name = "hiPinNumber")
    protected Integer hiPinNumber;
    @XmlAttribute(name = "hiPinChar")
    protected String hiPinChar;

    /**
     * Gets the value of the parameter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parameter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPARAMETER().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PARAMETER }
     * 
     * 
     */
    public List<PARAMETER> getPARAMETER() {
        if (parameter == null) {
            parameter = new ArrayList<PARAMETER>();
        }
        return this.parameter;
    }

    /**
     * Gets the value of the emitterid property.
     * 
     */
    public int getEmitterid() {
        return emitterid;
    }

    /**
     * Sets the value of the emitterid property.
     * 
     */
    public void setEmitterid(int value) {
        this.emitterid = value;
    }

    /**
     * Gets the value of the equipmentCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEquipmentCode() {
        return equipmentCode;
    }

    /**
     * Sets the value of the equipmentCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEquipmentCode(String value) {
        this.equipmentCode = value;
    }

    /**
     * Gets the value of the emitterName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmitterName() {
        return emitterName;
    }

    /**
     * Sets the value of the emitterName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmitterName(String value) {
        this.emitterName = value;
    }

    /**
     * Gets the value of the side property.
     * 
     */
    public int getSide() {
        return side;
    }

    /**
     * Sets the value of the side property.
     * 
     */
    public void setSide(int value) {
        this.side = value;
    }

    /**
     * Gets the value of the busfunction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusfunction() {
        return busfunction;
    }

    /**
     * Sets the value of the busfunction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusfunction(String value) {
        this.busfunction = value;
    }

    /**
     * Gets the value of the inlay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInlay() {
        return inlay;
    }

    /**
     * Sets the value of the inlay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInlay(String value) {
        this.inlay = value;
    }

    /**
     * Gets the value of the hiPinNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHiPinNumber() {
        return hiPinNumber;
    }

    /**
     * Sets the value of the hiPinNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHiPinNumber(Integer value) {
        this.hiPinNumber = value;
    }

    /**
     * Gets the value of the hiPinChar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHiPinChar() {
        return hiPinChar;
    }

    /**
     * Sets the value of the hiPinChar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHiPinChar(String value) {
        this.hiPinChar = value;
    }

	public void setPARAMETER(List<PARAMETER> parameter) {
		this.parameter = parameter;
	}

    
}
