//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.03 at 10:24:08 PM CET 
//


package com.airbus.alten.cacau.model.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}AUTHOR" maxOccurs="unbounded"/>
 *         &lt;element ref="{}REFERENCE"/>
 *         &lt;element ref="{}RELEASE"/>
 *         &lt;element ref="{}HLDOCUMENT" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "author",
    "reference",
    "release",
    "hldocument"
})
@XmlRootElement(name = "HEADER")
public class HEADER {

    @XmlElement(name = "AUTHOR", required = true)
    protected List<AUTHOR> author;
    @XmlElement(name = "REFERENCE", required = true)
    protected REFERENCE reference;
    @XmlElement(name = "RELEASE", required = true)
    protected RELEASE release;
    @XmlElement(name = "HLDOCUMENT", required = true)
    protected List<HLDOCUMENT> hldocument;

    /**
     * Gets the value of the author property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the author property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAUTHOR().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AUTHOR }
     * 
     * 
     */
    public List<AUTHOR> getAUTHOR() {
        if (author == null) {
            author = new ArrayList<AUTHOR>();
        }
        return this.author;
    }
    
    

    public void setAUTHOR(List<AUTHOR> author) {
		this.author = author;
	}



	/**
     * Gets the value of the reference property.
     * 
     * @return
     *     possible object is
     *     {@link REFERENCE }
     *     
     */
    public REFERENCE getREFERENCE() {
        return reference;
    }

    /**
     * Sets the value of the reference property.
     * 
     * @param value
     *     allowed object is
     *     {@link REFERENCE }
     *     
     */
    public void setREFERENCE(REFERENCE value) {
        this.reference = value;
    }

    /**
     * Gets the value of the release property.
     * 
     * @return
     *     possible object is
     *     {@link RELEASE }
     *     
     */
    public RELEASE getRELEASE() {
        return release;
    }

    /**
     * Sets the value of the release property.
     * 
     * @param value
     *     allowed object is
     *     {@link RELEASE }
     *     
     */
    public void setRELEASE(RELEASE value) {
        this.release = value;
    }

    /**
     * Gets the value of the hldocument property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hldocument property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHLDOCUMENT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HLDOCUMENT }
     * 
     * 
     */
    public List<HLDOCUMENT> getHLDOCUMENT() {
        if (hldocument == null) {
            hldocument = new ArrayList<HLDOCUMENT>();
        }
        return this.hldocument;
    }



	public void setHLDOCUMENT(List<HLDOCUMENT> hldocument) {
		this.hldocument = hldocument;
	}
    
    

}
