//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.03 at 10:24:08 PM CET 
//


package com.airbus.alten.cacau.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute ref="{}labelId use="required""/>
 *       &lt;attribute ref="{}numberOctal use="required""/>
 *       &lt;attribute ref="{}order"/>
 *       &lt;attribute ref="{}sdi"/>
 *       &lt;attribute ref="{}msb"/>
 *       &lt;attribute ref="{}len"/>
 *       &lt;attribute ref="{}signed"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "LABEL")
public class LABEL {

    @XmlAttribute(name = "labelId", required = true)
    protected int labelId;
    @XmlAttribute(name = "numberOctal", required = true)
    protected String numberOctal;
    @XmlAttribute(name = "order")
    protected Integer order;
    @XmlAttribute(name = "sdi")
    protected String sdi;
    @XmlAttribute(name = "msb")
    protected Integer msb;
    @XmlAttribute(name = "len")
    protected Integer len;
    @XmlAttribute(name = "signed")
    protected String signed;

    /**
     * Gets the value of the labelId property.
     * 
     */
    public int getLabelId() {
        return labelId;
    }

    /**
     * Sets the value of the labelId property.
     * 
     */
    public void setLabelId(int value) {
        this.labelId = value;
    }

    /**
     * Gets the value of the numberOctal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOctal() {
        return numberOctal;
    }

    /**
     * Sets the value of the numberOctal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOctal(String value) {
        this.numberOctal = value;
    }

    /**
     * Gets the value of the order property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOrder() {
        return order;
    }

    /**
     * Sets the value of the order property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setOrder(Integer value) {
        this.order = value;
    }

    /**
     * Gets the value of the sdi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSdi() {
        return sdi;
    }

    /**
     * Sets the value of the sdi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSdi(String value) {
        this.sdi = value;
    }

    /**
     * Gets the value of the msb property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMsb() {
        return msb;
    }

    /**
     * Sets the value of the msb property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMsb(Integer value) {
        this.msb = value;
    }

    /**
     * Gets the value of the len property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLen() {
        return len;
    }

    /**
     * Sets the value of the len property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLen(Integer value) {
        this.len = value;
    }

    /**
     * Gets the value of the signed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSigned() {
        return signed;
    }

    /**
     * Sets the value of the signed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSigned(String value) {
        this.signed = value;
    }

}
