//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.03 at 10:24:08 PM CET 
//


package com.airbus.alten.cacau.model.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link HLDOCUMENT }
     * 
     */
    public HLDOCUMENT createHLDOCUMENT() {
        return new HLDOCUMENT();
    }

    /**
     * Create an instance of {@link CONFIGURATION }
     * 
     */
    public CONFIGURATION createCONFIGURATION() {
        return new CONFIGURATION();
    }

    /**
     * Create an instance of {@link CONTENT }
     * 
     */
    public CONTENT createCONTENT() {
        return new CONTENT();
    }

    /**
     * Create an instance of {@link APPLICABILITY }
     * 
     */
    public APPLICABILITY createAPPLICABILITY() {
        return new APPLICABILITY();
    }

    /**
     * Create an instance of {@link PROGRAM }
     * 
     */
    public PROGRAM createPROGRAM() {
        return new PROGRAM();
    }

    /**
     * Create an instance of {@link AIRLINE }
     * 
     */
    public AIRLINE createAIRLINE() {
        return new AIRLINE();
    }

    /**
     * Create an instance of {@link EQUIPMENT }
     * 
     */
    public EQUIPMENT createEQUIPMENT() {
        return new EQUIPMENT();
    }

    /**
     * Create an instance of {@link EMITTER }
     * 
     */
    public EMITTER createEMITTER() {
        return new EMITTER();
    }

    /**
     * Create an instance of {@link PARAMETER }
     * 
     */
    public PARAMETER createPARAMETER() {
        return new PARAMETER();
    }

    /**
     * Create an instance of {@link LABEL }
     * 
     */
    public LABEL createLABEL() {
        return new LABEL();
    }

    /**
     * Create an instance of {@link EXPLORATION }
     * 
     */
    public EXPLORATION createEXPLORATION() {
        return new EXPLORATION();
    }

    /**
     * Create an instance of {@link DUMMY }
     * 
     */
    public DUMMY createDUMMY() {
        return new DUMMY();
    }

    /**
     * Create an instance of {@link YPBATCH }
     * 
     */
    public YPBATCH createYPBATCH() {
        return new YPBATCH();
    }

    /**
     * Create an instance of {@link USECASE }
     * 
     */
    public USECASE createUSECASE() {
        return new USECASE();
    }

    /**
     * Create an instance of {@link HEADER }
     * 
     */
    public HEADER createHEADER() {
        return new HEADER();
    }

    /**
     * Create an instance of {@link AUTHOR }
     * 
     */
    public AUTHOR createAUTHOR() {
        return new AUTHOR();
    }

    /**
     * Create an instance of {@link REFERENCE }
     * 
     */
    public REFERENCE createREFERENCE() {
        return new REFERENCE();
    }

    /**
     * Create an instance of {@link RELEASE }
     * 
     */
    public RELEASE createRELEASE() {
        return new RELEASE();
    }

}
