//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.03 at 10:24:08 PM CET 
//


package com.airbus.alten.cacau.model.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}LABEL" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{}parameterId use="required""/>
 *       &lt;attribute ref="{}ypparameterId use="required""/>
 *       &lt;attribute ref="{}parameterName use="required""/>
 *       &lt;attribute ref="{}description use="required""/>
 *       &lt;attribute ref="{}minSamplingFreq use="required""/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "label"
})
@XmlRootElement(name = "PARAMETER")
public class PARAMETER {

    @XmlElement(name = "LABEL", required = true)
    protected List<LABEL> label;
    @XmlAttribute(name = "parameterId", required = true)
    protected int parameterId;
    @XmlAttribute(name = "ypparameterId", required = true)
    protected String ypparameterId;
    @XmlAttribute(name = "parameterName", required = true)
    protected String parameterName;
    @XmlAttribute(name = "description", required = true)
    protected String description;
    @XmlAttribute(name = "minSamplingFreq", required = true)
    protected int minSamplingFreq;

    /**
     * Gets the value of the label property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the label property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLABEL().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LABEL }
     * 
     * 
     */
    public List<LABEL> getLABEL() {
        if (label == null) {
            label = new ArrayList<LABEL>();
        }
        return this.label;
    }

    /**
     * Gets the value of the parameterId property.
     * 
     */
    public int getParameterId() {
        return parameterId;
    }

    /**
     * Sets the value of the parameterId property.
     * 
     */
    public void setParameterId(int value) {
        this.parameterId = value;
    }

    /**
     * Gets the value of the ypparameterId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYpparameterId() {
        return ypparameterId;
    }

    /**
     * Sets the value of the ypparameterId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYpparameterId(String value) {
        this.ypparameterId = value;
    }

    /**
     * Gets the value of the parameterName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParameterName() {
        return parameterName;
    }

    /**
     * Sets the value of the parameterName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParameterName(String value) {
        this.parameterName = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the minSamplingFreq property.
     * 
     */
    public int getMinSamplingFreq() {
        return minSamplingFreq;
    }

    /**
     * Sets the value of the minSamplingFreq property.
     * 
     */
    public void setMinSamplingFreq(int value) {
        this.minSamplingFreq = value;
    }

	public void setLABEL(List<LABEL> label) {
		this.label = label;
	}
    
    

}
