//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.03 at 10:24:08 PM CET 
//


package com.airbus.alten.cacau.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute ref="{}actype use="required""/>
 *       &lt;attribute ref="{}enginesupplier use="required""/>
 *       &lt;attribute ref="{}enginetype use="required""/>
 *       &lt;attribute ref="{}aputype use="required""/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "PROGRAM")
public class PROGRAM {

    @XmlAttribute(name = "actype", required = true)
    protected String actype;
    @XmlAttribute(name = "enginesupplier", required = true)
    protected String enginesupplier;
    @XmlAttribute(name = "enginetype", required = true)
    protected String enginetype;
    @XmlAttribute(name = "aputype", required = true)
    protected String aputype;

    /**
     * Gets the value of the actype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActype() {
        return actype;
    }

    /**
     * Sets the value of the actype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActype(String value) {
        this.actype = value;
    }

    /**
     * Gets the value of the enginesupplier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnginesupplier() {
        return enginesupplier;
    }

    /**
     * Sets the value of the enginesupplier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnginesupplier(String value) {
        this.enginesupplier = value;
    }

    /**
     * Gets the value of the enginetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnginetype() {
        return enginetype;
    }

    /**
     * Sets the value of the enginetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnginetype(String value) {
        this.enginetype = value;
    }

    /**
     * Gets the value of the aputype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAputype() {
        return aputype;
    }

    /**
     * Sets the value of the aputype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAputype(String value) {
        this.aputype = value;
    }

}
